Controllers/ActorsController.cs
using x_sinema.Constans;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using x_sinema.Services;
using x_sinema.Models;

namespace x_sinema.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class ActorsController : Controller
    {
        private readonly IActorsService _actorService;

        public ActorsController(IActorsService actorService)
        {
            _actorService = actorService;
        }

        // mengambil data actor by id
        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Detail(int id)
        {
            var actorData = await _actorService.GetByIdAsync(id);

            if (actorData == null) return View("NotFound");
            return View(actorData);
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var allActorData = await _actorService.GetAllAsync();
            return View(allActorData);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add([Bind("FullName,ProfilePictureURL,Bio")] ActorModel actor)
        {
            if (!ModelState.IsValid)
            {
                return View(actor);
            }
            await _actorService.AddAsync(actor);
            TempData["message"] = MyFlasher.flasher("Actor data added successfully", berhasil: true);

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var actorData = await _actorService.GetByIdAsync(id);
            if (actorData == null) return View("NotFound");
            return View(actorData);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FullName,ProfilePictureURL,Bio")] ActorModel actor)
        {
            if (!ModelState.IsValid)
            {
                TempData["message"] = MyFlasher.flasher("Oops, error was found!", gagal: true);
                return View(actor);
            }
            await _actorService.UpdateAsync(id, actor);
            TempData["message"] = MyFlasher.flasher("Actor data update successfully", berhasil: true);

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var actorData = await _actorService.GetByIdAsync(id);
            if (actorData == null) return View("NotFound");
            return View(actorData);
        }

        [HttpPost]
        public async Task<IActionResult> DeletePost(int id)
        {
            var actorData = await _actorService.GetByIdAsync(id);
            if (actorData == null) return View("NotFound");

            await _actorService.DeleteAsync(id);
            TempData["message"] = MyFlasher.flasher("Actor data deleted successfully", berhasil: true);

            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/CompaniesController.cs
using x_sinema.Constans;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using x_sinema.Services;
using x_sinema.Models;

namespace x_sinema.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class CompaniesController : Controller
    {
        private readonly ICompaniesService _companiesService;

        public CompaniesController(ICompaniesService companiesService)
        {
            _companiesService = companiesService;
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var allCompaniesData = await _companiesService.GetAllAsync();
            return View(allCompaniesData);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var companyData = await _companiesService.GetByIdAsync(id);
            if (companyData == null) return View("NotFound");
            return View(companyData);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Logo,Name,Description")] CompanyModel companyModel)
        {
            if (!ModelState.IsValid) return View(companyModel);
            await _companiesService.UpdateAsync(id, companyModel);
            TempData["message"] = MyFlasher.flasher("Company data update successfully", berhasil: true);

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Detail(int id)
        {
            var companyData = await _companiesService.GetByIdAsync(id);
            if (companyData == null) return View("NotFound");
            return View(companyData);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add([Bind("Logo,Name,Description")] CompanyModel companyModel)
        {
            if (!ModelState.IsValid)
            {
                TempData["message"] = MyFlasher.flasher("Oops error was found", gagal: true);

                return View(companyModel);
            }

            await _companiesService.AddAsync(companyModel);
            TempData["message"] = MyFlasher.flasher("Company data <strong>updated</strong> successfully", berhasil: true);

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var companyData = await _companiesService.GetByIdAsync(id);
            if (companyData == null) return View("NotFound");
            return View(companyData);
        }

        [HttpPost]
        public async Task<IActionResult> DeletePost(int id)
        {
            var companyData = await _companiesService.GetByIdAsync(id);
            if (companyData == null) return View("NotFound");

            await _companiesService.DeleteAsync(id);
            TempData["message"] = MyFlasher.flasher("Company data <strong>deleted</strong> successfully", berhasil: true);

            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/OrdersController.cs
using x_sinema.Services;
using x_sinema.Constans;
using x_sinema.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using x_sinema.Servies;

namespace x_sinema.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly IMoviesService _moviesService;
        private readonly Cart _cart;
        private readonly IOrdersService _ordersService;

        public OrdersController(IMoviesService moviesService, Cart shoppingCart, IOrdersService ordersService)
        {
            _moviesService = moviesService;
            _cart = shoppingCart;
            _ordersService = ordersService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);

            var orders = await _ordersService.GetOrdersByUserIdAndRoleAsync(userId, userRole);
            return View(orders);
        }

        [HttpGet]
        public async Task<IActionResult> DetailOrder(int id)
        {
            var orderData = await _ordersService.GetOrderByIdAsync(id);
            return View(orderData);
        }

        public IActionResult CartSummary()
        {
            var items = _cart.GetCartItems();
            _cart.CartItems = items;

            var cartViewModel = new CartViewModel()
            {
                Cart = _cart,
                CartTotal = _cart.GetCartTotal()
            };

            return View(cartViewModel);
        }

        public async Task<IActionResult> AddItemToCart(int id)
        {
            var item = await _moviesService.GetMovieByIdAsync(id);

            if (item != null)
            {
                _cart.AddItemToCart(item);
            }
            return RedirectToAction(nameof(CartSummary));
        }

        public async Task<IActionResult> RemoveItemFromCart(int id)
        {
            var item = await _moviesService.GetMovieByIdAsync(id);

            if (item != null)
            {
                _cart.RemoveItemFromCart(item);
            }
            return RedirectToAction(nameof(CartSummary));
        }

        public async Task<IActionResult> Checkout()
        {
            var items = _cart.GetCartItems();
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userEmailAddress = User.FindFirstValue(ClaimTypes.Email);

            await _ordersService.StoreOrderAsync(items, userId, userEmailAddress);
            await _cart.ClearCartAsync();
            TempData["message"] = MyFlasher.flasher("Order data <strong>store</strong> successfully into order history", berhasil: true);

            return RedirectToAction("Index", "Movies");
        }
    }
}

Controllers/ProducersController.cs
using x_sinema.Constans;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using x_sinema.Services;
using x_sinema.Models;

namespace x_sinema.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class ProducersController : Controller
    {
        private readonly IProducersService _producerService;

        public ProducersController(IProducersService producerService)
        {
            _producerService = producerService;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var allProducersData = await _producerService.GetAllAsync();
            return View(allProducersData);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add([Bind("ProfilePictureURL,FullName,Bio")] ProducerModel producerModel)
        {
            if (!ModelState.IsValid)
            {
                TempData["message"] = MyFlasher.flasher("Oops, error was found!", gagal: true);
                return View(producerModel);
            }

            await _producerService.AddAsync(producerModel);
            TempData["message"] = MyFlasher.flasher("Producer data added successfully", berhasil: true);

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var producerData = await _producerService.GetByIdAsync(id);
            if (producerData == null) return View("NotFound");
            return View(producerData);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ProfilePictureURL,FullName,Bio")] ProducerModel producerModel)
        {
            if (!ModelState.IsValid)
            {
                TempData["message"] = MyFlasher.flasher("Oops error was found", gagal: true);
                return View(producerModel);
            }

            await _producerService.UpdateAsync(id, producerModel);
            TempData["message"] = MyFlasher.flasher("Producer data <strong>updated</strong> successfully", berhasil: true);

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Detail(int id)
        {
            var producerData = await _producerService.GetByIdAsync(id);
            if (producerData == null) return View("NotFound");
            return View(producerData);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var producerData = await _producerService.GetByIdAsync(id);
            if (producerData == null) return View("NotFound");
            return View(producerData);
        }

        [HttpPost]
        public async Task<IActionResult> DeletePost(int id)
        {
            var producerData = await _producerService.GetByIdAsync(id);
            if (producerData == null) return View("NotFound");

            await _producerService.DeleteAsync(id);
            TempData["message"] = MyFlasher.flasher("Movie data <strong>deleted</strong> successfully", berhasil: true);

            return RedirectToAction(nameof(Index));
        }
    }
}

Views/Shared/_ButtonAddPartial.cshtml
@model string
<div class="d-flex justify-content-end mb-3">
    @if (@Model != "Movies")
    {
        <a class="btn btn-outline-secondary me-2" asp-controller="Movies" asp-action="Index">Back to Home</a>
    }
    @if (User.Identity!.IsAuthenticated && User.IsInRole("Admin"))
    {
        <a class="btn btn-success" asp-controller="@Model" asp-action="Add">Add New Data</a>
    }
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel='stylesheet prefetch' href='https://fonts.googleapis.com/icon?family=Material+Icons'>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    <!-- sweetalert CDN -->
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    @*custom css in each layout if exist*@
    @if (@ViewData["css"] != null)
    {
        <link rel="stylesheet" href="~/css/@ViewData["css"]" asp-append-version="true" />
    }
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-dark">
        <div class="container">
            <a class="navbar-brand text-white" asp-area="" asp-controller="Movies" asp-action="Index">X-Sinema</a>
            <button class="navbar-toggler bg-white" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-area="" asp-controller="Movies" asp-action="Index">Movies</a>
                    </li>
                    @if (User.Identity!.IsAuthenticated)
                    {
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="Orders" asp-action="Index">History Orders</a>
                        </li>
                    }
                    @if (User.Identity!.IsAuthenticated && User.IsInRole("Customer"))
                    {
                        <li class="nav-item">
                            @await Component.InvokeAsync("CurrentCheckoutItems")
                        </li>

                    }
                    @if (User.Identity!.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Interface
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" asp-controller="Companies" asp-action="Index">Companies</a></li>
                                <li><a class="dropdown-item" asp-controller="Producers" asp-action="Index">Producers</a></li>
                                <li><a class="dropdown-item" asp-controller="Actors" asp-action="Index">Actors</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" asp-controller="Admin" asp-action="ListOfUsers">List of Users</a></li>
                            </ul>
                        </li>
                    }
                </ul>
                <form class="d-flex me-3" role="search" asp-controller="Movies" asp-action="Search">
                    <input class="form-control me-2 " name="search" type="search" placeholder="Search movie" aria-label="Search">
                    <button class="btn btn-outline-info" type="submit">Search</button>
                </form>
                <partial name="_LoginPartial" />

            </div>
        </div>
    </nav>
    <div class="container">
        @if (TempData["message"] != null)
        {
            @Html.Raw(@TempData["message"])
        }

        @if (ViewData["controller"] != null)
        {
            <nav aria-label="breadcrumb" class="main-breadcrumb mt-4">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">Home</li>
                    <li class="breadcrumb-item">@ViewData["controller"]</li>
                    <li class="breadcrumb-item active" aria-current="page">@ViewData["action"]</li>
                </ol>
            </nav>

            <hr>
        }
        @RenderBody()
    </div>

    <footer class="py-4 bg-light mt-auto mb-0">
        <div class="container-fluid px-4">
            <div class="d-flex align-items-center justify-content-center small">
                Copyright &copy; X-Sinema 2022
            </div>
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    <script src="@Url.Content("~/js/scripts.js")" type="text/javascript"></script>
    <partial name="_ValidationScriptsPartial" />
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>